name: Configure CORS

on:
  push:
    branches:
      - main  # Cambia a la rama principal de tu repositorio si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure CORS
        uses: pennlabs/pages-cors-proxy@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cors-file: cors.json
